# Generated by Django 6.0.3 on 2026-04-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
