# Generated by Django 6.0.3 on 2026-04-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
