# Generated by Django 6.0.3 on 2026-04-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_customer_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
    ]
