# Generated by Django 6.0.3 on 2026-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
    ]
