# Generated by Django 6.0.3 on 2026-05-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_order_address_remove_order_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
