# Generated by Django 6.0.4 on 2026-05-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
