# Generated by Django 6.0.3 on 2026-05-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_order_created_at_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
