# Generated by Django 6.0.3 on 2026-05-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
